<?php

namespace FondOfSpryker\Shared\ActiveCampaign;

interface ActiveCampaignConstants
{
    const ACTIVE_CAMPAIGN_API_KEY = 'ACTIVE_CAMPAIGN_API_KEY';

    const ACTIVE_CAMPAIGN_URL = 'ACTIVE_CAMPAIGN_URL';

    const ACTIVE_CAMPAIGN_FORMID = 'ACTIVE_CAMPAIGN_FORMID';

    const ACTIVE_CAMPAIGN_LISTID = 'ACTIVE_CAMPAIGN_LISTID';

    const ACTIVE_CAMPAIGN_SUBSCRIBE_URL = 'ACTIVE_CAMPAIGN_SUBSCRIBE_URL';

    const ACTIVE_CAMPAIGN_CONFIRMATION_URL = 'ACTIVE_CAMPAIGN_CONFIRMATION_URL';

    const ACTIVE_CAMPAIGN_SUBSCRIBE_CONFIRM_URL = 'ACTIVE_CAMPAIGN_SUBSCRIBE_CONFIRM_URL';

    const URL_NEWSLETTER_CONFIRMED = 'URL_NEWSLETTER_CONFIRMED';

    const URL_NEWSLETTER_SUBSCRIBE = 'URL_NEWSLETTER_SUBSCRIBE';
}
