<?php

namespace FondOfSpryker\Shared\ActiveCampaign;

interface ActiveCampaignConstants
{
    public const ACTIVE_CAMPAIGN_API_KEY = 'ACTIVE_CAMPAIGN_API_KEY';
    public const ACTIVE_CAMPAIGN_URL = 'ACTIVE_CAMPAIGN_URL';
    public const ACTIVE_CAMPAIGN_FORM_ID = 'ACTIVE_CAMPAIGN_FORM_ID';
    public const ACTIVE_CAMPAIGN_LIST_ID = 'ACTIVE_CAMPAIGN_LIST_ID';
    public const ACTIVE_CAMPAIGN_LOCALIZED_CONFIGS = 'ACTIVE_CAMPAIGN_LOCALIZED_CONFIGS';
    public const ACTIVE_CAMPAIGN_SUBSCRIBE_PATH = 'ACTIVE_CAMPAIGN_SUBSCRIBE_PATH';
    public const ACTIVE_CAMPAIGN_CONFIRMATION_PATH = 'ACTIVE_CAMPAIGN_CONFIRMATION_PATH';
}
